/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Sparkles, Camera as CameraIcon, Upload, ArrowRight, Loader2, Heart, Palette, User, Info, X, Download, Search, Sun } from 'lucide-react';
import { Camera } from './components/Camera';
import { analyzeFace, MakeupRecommendation } from './services/gemini';
import Markdown from 'react-markdown';

type AppState = 'home' | 'camera' | 'analyzing' | 'results';
type ModalType = 'none' | 'how-it-works' | 'privacy' | 'about';

export default function App() {
  const [state, setState] = useState<AppState>('home');
  const [activeModal, setActiveModal] = useState<ModalType>('none');
  const [image, setImage] = useState<string | null>(null);
  const [result, setResult] = useState<MakeupRecommendation | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleCapture = async (capturedImage: string) => {
    setImage(capturedImage);
    setState('analyzing');
    try {
      const recommendation = await analyzeFace(capturedImage);
      setResult(recommendation);
      setState('results');
    } catch (err) {
      console.error(err);
      setError("Failed to analyze image. Please try again.");
      setState('home');
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        handleCapture(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const reset = () => {
    setState('home');
    setImage(null);
    setResult(null);
    setError(null);
  };

  const downloadGuide = () => {
    if (!result) return;

    const content = `
GLOWGUIDE AI - YOUR PERSONAL BEAUTY GUIDE
==========================================

YOUR PROFILE:
-------------
- Skin Tone: ${result.skinTone}
- Undertone: ${result.undertone}
- Face Shape: ${result.faceShape}
- Skin Type: ${result.skinType}

RECOMMENDATIONS:
----------------
- Foundation & Base: ${result.recommendations.foundation}
- Lip Color: ${result.recommendations.lipstick}
- Eyeshadow Palette: ${result.recommendations.eyeshadow}
- Blush & Glow: ${result.recommendations.blush}
- Overall Style: ${result.recommendations.overallStyle}

EXPLANATION & TIPS:
-------------------
${result.explanation.replace(/#/g, '').trim()}

==========================================
Generated by GlowGuide AI on ${new Date().toLocaleDateString()}
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `GlowGuide_Beauty_Plan.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen flex flex-col">
      {/* Navigation */}
      <nav className="p-6 flex justify-between items-center max-w-7xl mx-auto w-full">
        <div className="flex items-center gap-2 cursor-pointer" onClick={reset}>
          <div className="w-10 h-10 bg-brand-olive rounded-full flex items-center justify-center text-white shadow-lg">
            <Sparkles size={20} />
          </div>
          <span className="serif text-2xl font-semibold tracking-tight">GlowGuide AI</span>
        </div>
        <div className="hidden md:flex gap-8 text-sm uppercase tracking-widest font-medium opacity-60">
          <button onClick={() => setActiveModal('how-it-works')} className="hover:opacity-100 transition-opacity cursor-pointer">How it works</button>
          <button onClick={() => setActiveModal('privacy')} className="hover:opacity-100 transition-opacity cursor-pointer">Privacy</button>
          <button onClick={() => setActiveModal('about')} className="hover:opacity-100 transition-opacity cursor-pointer">About</button>
        </div>
      </nav>

      <AnimatePresence>
        {activeModal !== 'none' && (
          <Modal type={activeModal} onClose={() => setActiveModal('none')} />
        )}
      </AnimatePresence>

      <main className="flex-grow flex flex-col items-center justify-center px-6 py-12">
        <AnimatePresence mode="wait">
          {state === 'home' && (
            <motion.div
              key="home"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="max-w-4xl w-full text-center space-y-12"
            >
              <div className="space-y-6">
                <h1 className="serif text-6xl md:text-8xl leading-[0.9] font-light tracking-tight">
                  Your beauty, <br />
                  <span className="italic">reimagined</span> by AI.
                </h1>
                <p className="text-lg md:text-xl text-brand-ink/60 max-w-xl mx-auto font-light leading-relaxed">
                  Discover the perfect shades and styles for your unique features. 
                  Our AI analyzes your skin tone and face shape to curate a personalized makeup guide.
                </p>
              </div>

              <div className="flex flex-col md:flex-row items-center justify-center gap-6 pt-8">
                <button
                  onClick={() => setState('camera')}
                  className="group relative flex items-center gap-3 px-10 py-5 bg-brand-olive text-white rounded-full text-lg font-medium shadow-xl hover:scale-105 transition-all active:scale-95"
                >
                  <CameraIcon size={24} />
                  <span>Take a Selfie</span>
                  <div className="absolute -inset-1 bg-brand-olive/20 rounded-full blur-lg group-hover:blur-xl transition-all" />
                </button>

                <label className="flex items-center gap-3 px-10 py-5 bg-white border border-brand-ink/10 text-brand-ink rounded-full text-lg font-medium cursor-pointer hover:bg-brand-cream transition-colors shadow-sm">
                  <Upload size={24} />
                  <span>Upload Photo</span>
                  <input type="file" accept="image/*" className="hidden" onChange={handleFileUpload} />
                </label>
              </div>

              {error && (
                <p className="text-red-500 font-medium">{error}</p>
              )}

              <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pt-24 border-t border-brand-ink/5">
                {[
                  { icon: <Palette size={24} />, title: "Color Theory", desc: "Precise undertone analysis for perfect matches." },
                  { icon: <User size={24} />, title: "Face Mapping", desc: "Recommendations tailored to your unique structure." },
                  { icon: <Heart size={24} />, title: "Curated Styles", desc: "From natural glow to evening glam, just for you." }
                ].map((feature, i) => (
                  <div key={i} className="space-y-4 text-left p-6 rounded-3xl bg-white/50 backdrop-blur-sm border border-white/20">
                    <div className="text-brand-olive">{feature.icon}</div>
                    <h3 className="serif text-xl font-semibold">{feature.title}</h3>
                    <p className="text-sm text-brand-ink/60 leading-relaxed">{feature.desc}</p>
                  </div>
                ))}
              </div>
            </motion.div>
          )}

          {state === 'camera' && (
            <Camera onCapture={handleCapture} onCancel={() => setState('home')} />
          )}

          {state === 'analyzing' && (
            <motion.div
              key="analyzing"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex flex-col items-center gap-8 text-center"
            >
              <div className="relative">
                <div className="w-32 h-32 border-4 border-brand-olive/20 rounded-full animate-pulse" />
                <div className="absolute inset-0 flex items-center justify-center">
                  <Loader2 className="animate-spin text-brand-olive" size={48} />
                </div>
              </div>
              <div className="space-y-2">
                <h2 className="serif text-3xl font-medium">Analyzing your features...</h2>
                <p className="text-brand-ink/60 italic">Gemini is curating your personalized beauty guide</p>
              </div>
            </motion.div>
          )}

          {state === 'results' && result && (
            <motion.div
              key="results"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="max-w-6xl w-full grid grid-cols-1 lg:grid-cols-12 gap-12"
            >
              {/* Left Column: Image and Profile */}
              <div className="lg:col-span-4 space-y-8">
                <div className="aspect-[3/4] rounded-[40px] overflow-hidden shadow-2xl border-8 border-white">
                  <img src={image!} alt="Your Profile" className="w-full h-full object-cover" />
                </div>
                
                <div className="bg-white rounded-[32px] p-8 shadow-sm space-y-6 border border-brand-ink/5">
                  <h3 className="serif text-2xl font-semibold border-bottom border-brand-ink/5 pb-4">Your Profile</h3>
                  <div className="space-y-4">
                    <ProfileItem label="Skin Tone" value={result.skinTone} />
                    <ProfileItem label="Undertone" value={result.undertone} />
                    <ProfileItem label="Face Shape" value={result.faceShape} />
                    <ProfileItem label="Skin Type" value={result.skinType} />
                  </div>
                </div>

                <div className="flex flex-col gap-4">
                  <button
                    onClick={downloadGuide}
                    className="w-full py-4 rounded-full bg-brand-olive text-white hover:scale-[1.02] transition-all font-medium flex items-center justify-center gap-2 shadow-lg"
                  >
                    <Download size={20} />
                    Download Guide
                  </button>
                  
                  <button
                    onClick={reset}
                    className="w-full py-4 rounded-full border border-brand-ink/10 hover:bg-brand-ink hover:text-white transition-all font-medium flex items-center justify-center gap-2"
                  >
                    <RefreshCw size={20} />
                    New Analysis
                  </button>
                </div>
              </div>

              {/* Right Column: Recommendations */}
              <div className="lg:col-span-8 space-y-8">
                <div className="space-y-2">
                  <span className="text-xs uppercase tracking-widest font-bold text-brand-olive">Personalized Guide</span>
                  <h2 className="serif text-5xl md:text-6xl font-light">Recommended for you</h2>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <RecCard 
                    title="Foundation & Base" 
                    content={result.recommendations.foundation} 
                    icon={<User size={20} />} 
                  />
                  <RecCard 
                    title="Lip Color" 
                    content={result.recommendations.lipstick} 
                    icon={<Heart size={20} />} 
                    swatch={result.recommendations.lipstickHex}
                  />
                  <RecCard 
                    title="Eyeshadow Palette" 
                    content={result.recommendations.eyeshadow} 
                    icon={<Palette size={20} />} 
                    swatch={result.recommendations.eyeshadowHex}
                  />
                  <RecCard 
                    title="Blush & Glow" 
                    content={result.recommendations.blush} 
                    icon={<Sparkles size={20} />} 
                    swatch={result.recommendations.blushHex}
                  />
                </div>

                <div className="bg-brand-olive text-white rounded-[40px] p-10 shadow-xl space-y-6">
                  <div className="flex items-center gap-3">
                    <Info size={24} />
                    <h3 className="serif text-3xl italic">Style: {result.recommendations.overallStyle}</h3>
                  </div>
                  <div className="prose-custom max-w-none opacity-90 leading-relaxed">
                    <Markdown>{result.explanation}</Markdown>
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      {/* Footer */}
      <footer className="p-12 border-t border-brand-ink/5 text-center space-y-4">
        <p className="serif text-xl italic opacity-60">"Beauty begins the moment you decide to be yourself."</p>
        <p className="text-xs uppercase tracking-[0.2em] opacity-40 font-bold">© 2026 GlowGuide AI</p>
      </footer>
    </div>
  );
}

function ProfileItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between items-center py-2 border-b border-brand-ink/5 last:border-0">
      <span className="text-sm font-semibold uppercase tracking-wider opacity-40">{label}</span>
      <span className="font-medium text-brand-olive">{value}</span>
    </div>
  );
}

function RecCard({ title, content, icon, swatch }: { title: string; content: string; icon: React.ReactNode; swatch?: string }) {
  const searchUrl = `https://www.google.com/search?q=${encodeURIComponent(content + ' makeup')}`;
  
  return (
    <div className="bg-white p-8 rounded-[32px] shadow-sm border border-brand-ink/5 space-y-4 hover:shadow-md transition-shadow group">
      <div className="flex justify-between items-start">
        <div className="flex items-center gap-3 text-brand-olive">
          {icon}
          <h4 className="font-bold uppercase tracking-widest text-xs">{title}</h4>
        </div>
        {swatch && (
          <div 
            className="w-8 h-8 rounded-full border border-brand-ink/10 shadow-inner" 
            style={{ backgroundColor: swatch }}
            title={`Recommended Shade: ${swatch}`}
          />
        )}
      </div>
      <p className="text-lg leading-relaxed text-brand-ink/80">{content}</p>
      <a 
        href={searchUrl} 
        target="_blank" 
        rel="noopener noreferrer"
        className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-brand-olive opacity-0 group-hover:opacity-100 transition-opacity"
      >
        <Search size={14} />
        Find Products
      </a>
    </div>
  );
}

function RefreshCw({ size }: { size: number }) {
  return (
    <svg 
      width={size} 
      height={size} 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth="2" 
      strokeLinecap="round" 
      strokeLinejoin="round"
    >
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M3 21v-5h5" />
    </svg>
  );
}

function Modal({ type, onClose }: { type: ModalType; onClose: () => void }) {
  const content = {
    'how-it-works': {
      title: 'How GlowGuide Works',
      body: `
### 1. Advanced Vision Analysis
When you take a selfie, our AI uses advanced computer vision to map your facial structure and identify key features.

### 2. Color Theory Integration
We analyze your skin's undertones (Cool, Warm, or Neutral) and overall tone to find colors that naturally complement your complexion.

### 3. Personalized Curation
Gemini Pro processes this data to curate a specific makeup palette, from foundation shades to lipstick colors, tailored specifically for you.
      `
    },
    'privacy': {
      title: 'Your Privacy Matters',
      body: `
### Real-time Processing
Your images are processed in real-time to generate recommendations. We do not store your photos on our servers permanently.

### Secure Analysis
All analysis is performed using secure API connections. Your personal data is used solely for providing beauty recommendations during your session.

### Control
You have full control over your camera and data. No information is shared with third parties without your explicit consent.
      `
    },
    'about': {
      title: 'About GlowGuide AI',
      body: `
### Beauty Reimagined
GlowGuide AI was born from the idea that beauty should be accessible and personalized. We leverage the latest in Artificial Intelligence to help you discover your best self.

### Our Mission
To empower individuals with professional-grade beauty advice through the power of technology. We believe everyone deserves to feel confident in their own skin.
      `
    }
  }[type as Exclude<ModalType, 'none'>];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-brand-ink/40 backdrop-blur-md"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0, y: 20 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.9, opacity: 0, y: 20 }}
        className="bg-white w-full max-w-2xl rounded-[40px] shadow-2xl overflow-hidden relative"
        onClick={(e) => e.stopPropagation()}
      >
        <button 
          onClick={onClose}
          className="absolute top-8 right-8 p-2 rounded-full hover:bg-brand-cream transition-colors text-brand-ink/40 hover:text-brand-ink"
        >
          <X size={24} />
        </button>
        
        <div className="p-12 space-y-8 text-center">
          <div className="space-y-2">
            <span className="text-xs uppercase tracking-widest font-bold text-brand-olive">Information</span>
            <h2 className="serif text-4xl font-medium">{content.title}</h2>
          </div>
          
          <div className="prose-custom max-w-none text-brand-ink/80 leading-relaxed mx-auto">
            <Markdown>{content.body}</Markdown>
          </div>

          <button
            onClick={onClose}
            className="w-full py-4 bg-brand-olive text-white rounded-full font-medium hover:scale-[1.02] transition-transform shadow-lg"
          >
            Got it
          </button>
        </div>
      </motion.div>
    </motion.div>
  );
}
