/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Sparkles, Camera as CameraIcon, Upload, ArrowRight, Loader2, Heart, Palette, User, Info, X, Download, Search, Sun, MessageCircle } from 'lucide-react';
import { Camera } from './components/Camera';
import { ChatBot } from './components/ChatBot';
import { AnimatedBackground } from './components/AnimatedBackground';
import { analyzeFace, MakeupRecommendation } from './services/gemini';
import Markdown from 'react-markdown';


type AppState = 'home' | 'camera' | 'analyzing' | 'results' | 'chat';
type ModalType = 'none' | 'how-it-works' | 'privacy' | 'about';

export default function App() {
  const [state, setState] = useState<AppState>('home');
  const [activeModal, setActiveModal] = useState<ModalType>('none');
  const [image, setImage] = useState<string | null>(null);
  const [result, setResult] = useState<MakeupRecommendation | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleCapture = async (capturedImage: string) => {
    setImage(capturedImage);
    setState('analyzing');
    try {
      const recommendation = await analyzeFace(capturedImage);
      setResult(recommendation);
      setState('results');
    } catch (err) {
      console.error(err);
      setError("Failed to analyze image. Please try again.");
      setState('home');
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        const img = new Image();
        img.onload = () => {
          const canvas = document.createElement('canvas');
          let width = img.width;
          let height = img.height;
          
          const MAX_SIZE = 800;
          if (width > height) {
            if (width > MAX_SIZE) {
              height *= MAX_SIZE / width;
              width = MAX_SIZE;
            }
          } else {
            if (height > MAX_SIZE) {
              width *= MAX_SIZE / height;
              height = MAX_SIZE;
            }
          }
          
          canvas.width = width;
          canvas.height = height;
          const ctx = canvas.getContext('2d');
          if (ctx) {
            ctx.drawImage(img, 0, 0, width, height);
            const compressedDateUrl = canvas.toDataURL('image/jpeg', 0.6);
            handleCapture(compressedDateUrl);
          } else {
            handleCapture(reader.result as string);
          }
        };
        img.src = reader.result as string;
      };
      reader.readAsDataURL(file);
    }
  };

  const reset = () => {
    setState('home');
    setImage(null);
    setResult(null);
    setError(null);
  };

  const downloadGuide = () => {
    if (!result) return;

    const content = `
GLOWGUIDE AI - YOUR PERSONAL BEAUTY GUIDE
==========================================

YOUR PROFILE:
-------------
- Skin Tone: ${result.skinTone}
- Undertone: ${result.undertone}
- Face Shape: ${result.faceShape}
- Skin Type: ${result.skinType}

RECOMMENDATIONS:
----------------
- Foundation & Base: ${result.recommendations.foundation}
- Lip Color: ${result.recommendations.lipstick}
- Eyeshadow Palette: ${result.recommendations.eyeshadow}
- Blush & Glow: ${result.recommendations.blush}
- Overall Style: ${result.recommendations.overallStyle}

EXPLANATION & TIPS:
-------------------
${result.explanation.replace(/#/g, '').trim()}

==========================================
Generated by GlowGuide AI on ${new Date().toLocaleDateString()}
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `GlowGuide_Beauty_Plan.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen flex flex-col relative z-0">
      <AnimatedBackground />
      {/* Navigation */}
      <nav className="p-6 flex justify-between items-center max-w-7xl mx-auto w-full relative z-10 text-white">
        <div className="flex items-center gap-2 cursor-pointer" onClick={reset}>
          <div className="w-10 h-10 bg-[#110714] border border-white/10 rounded-full flex items-center justify-center text-white shadow-[0_0_15px_rgba(255,255,255,0.1)]">
             <Sparkles size={18} />
          </div>
          <span className="serif text-2xl font-semibold tracking-tight">GlowGuide AI</span>
        </div>
        <div className="hidden md:flex gap-8 text-sm uppercase tracking-widest font-medium opacity-80">
          <button onClick={() => setActiveModal('how-it-works')} className="hover:opacity-100 transition-opacity cursor-pointer">How it works</button>
          <button onClick={() => setActiveModal('privacy')} className="hover:opacity-100 transition-opacity cursor-pointer">Privacy</button>
          <button onClick={() => setActiveModal('about')} className="hover:opacity-100 transition-opacity cursor-pointer">About</button>
        </div>
      </nav>

      <AnimatePresence>
        {activeModal !== 'none' && (
          <Modal type={activeModal} onClose={() => setActiveModal('none')} />
        )}
      </AnimatePresence>

      <main className="flex-grow flex flex-col items-center justify-center px-6 py-12 text-white">
        <AnimatePresence mode="wait">
          {state === 'home' && (
            <motion.div
              key="home"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="max-w-4xl w-full text-center space-y-12"
            >
              <div className="space-y-8 flex flex-col items-center">
                {/* Glowing Pill Badge */}
                <motion.div
                  className="px-5 py-2 rounded-full border border-[#e8609a]/30 bg-[#c0407a]/10 text-[#f5a8c8] text-xs md:text-sm uppercase tracking-[0.14em] font-medium flex items-center gap-2"
                  animate={{ boxShadow: ['0 0 0px rgba(232, 96, 154, 0)', '0 0 20px rgba(232, 96, 154, 0.4)', '0 0 0px rgba(232, 96, 154, 0)'] }}
                  transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
                >
                   <span className="text-lg leading-none">✦</span> Powered by AI beauty intelligence
                </motion.div>

                <h1 className="serif text-6xl md:text-8xl leading-[1.05] font-light tracking-tight text-white max-w-4xl pt-2">
                  Your beauty, <br />
                  <motion.span 
                    className="italic text-[#f5b8d4]" 
                    animate={{ textShadow: ['0 0 10px rgba(245, 184, 212, 0.3)', '0 0 25px rgba(245, 184, 212, 0.6)', '0 0 10px rgba(245, 184, 212, 0.3)'] }}
                    transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
                  >
                    reimagined
                  </motion.span> by AI.
                </h1>
                <p className="text-lg text-white/50 max-w-[400px] mx-auto font-light leading-relaxed">
                  Discover the perfect shades and styles for your unique features. 
                  Our AI analyzes your skin tone and face shape to curate a personalized makeup guide.
                </p>
              </div>

              <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-10">
                <button
                  onClick={() => setState('camera')}
                  className="relative overflow-hidden flex items-center justify-center gap-2 px-8 py-4 bg-gradient-to-r from-[#d4587e] to-[#e8a0c0] text-white rounded-full text-sm uppercase tracking-widest font-semibold shadow-[0_0_20px_rgba(232,160,192,0.3)] hover:shadow-[0_0_30px_rgba(232,160,192,0.5)] transition-all hover:scale-105 active:scale-95 group w-full sm:w-auto"
                >
                  <CameraIcon size={18} />
                  <span>Take a Selfie</span>
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-r from-transparent via-white/40 to-transparent -skew-x-12"
                    initial={{ left: '-100%' }}
                    animate={{ left: '200%' }}
                    transition={{ duration: 3, ease: 'easeOut', repeat: Infinity, repeatDelay: 1 }}
                  />
                </button>

                <label className="flex items-center justify-center gap-2 px-8 py-4 border border-white/20 hover:border-white/40 text-white rounded-full text-sm uppercase tracking-widest font-semibold cursor-pointer hover:bg-white/5 transition-all w-full sm:w-auto">
                  <Upload size={18} />
                  <span>Upload Photo</span>
                  <input type="file" accept="image/*" className="hidden" onChange={handleFileUpload} />
                </label>

                <button
                  onClick={() => setState('chat')}
                  className="flex items-center justify-center gap-2 px-8 py-4 border border-[#e8609a]/40 text-[#f5a8c8] hover:bg-[#e8609a]/10 rounded-full text-sm uppercase tracking-widest font-semibold transition-all w-full sm:w-auto"
                >
                  <MessageCircle size={18} />
                  <span>Chat Only</span>
                </button>
              </div>

              {error && (
                <p className="text-red-400 font-medium">{error}</p>
              )}

              <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pt-24 border-t border-white/10">
                {[
                  { icon: <Palette size={24} />, title: "Color Theory", desc: "Precise undertone analysis for perfect matches." },
                  { icon: <User size={24} />, title: "Face Mapping", desc: "Recommendations tailored to your unique structure." },
                  { icon: <Heart size={24} />, title: "Curated Styles", desc: "From natural glow to evening glam, just for you." }
                ].map((feature, i) => (
                  <div key={i} className="space-y-4 text-left p-6 rounded-3xl bg-[#ffffff05] backdrop-blur-md border border-white/10 shadow-2xl transition hover:bg-[#ffffff08]">
                    <div className="text-[#f5a8c8] mt-2 inline-block p-3 rounded-xl bg-white/5">{feature.icon}</div>
                    <h3 className="serif text-2xl font-medium text-white/90">{feature.title}</h3>
                    <p className="text-sm text-white/50 leading-relaxed font-light">{feature.desc}</p>
                  </div>
                ))}
              </div>
            </motion.div>
          )}

          {state === 'camera' && (
            <motion.div
              key="camera"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="w-full flex justify-center"
            >
              <Camera onCapture={handleCapture} onCancel={() => setState('home')} />
            </motion.div>
          )}

          {state === 'chat' && (
            <motion.div
              key="chat"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="w-full flex justify-center"
            >
              <ChatBot onClose={() => setState('home')} />
            </motion.div>
          )}

          {state === 'analyzing' && (
            <motion.div
              key="analyzing"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex flex-col items-center gap-8 text-center"
            >
              <div className="relative">
                {/* Outer pulsing ring */}
                <motion.div 
                  className="w-32 h-32 border-2 border-white/20 rounded-full"
                  animate={{ scale: [1, 1.2, 1], opacity: [0.3, 0, 0.3] }}
                  transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
                />
                {/* Inner scanning ring */}
                <motion.div 
                  className="absolute inset-0 w-32 h-32 border-t-2 border-white rounded-full"
                  animate={{ rotate: 360 }}
                  transition={{ duration: 1.5, repeat: Infinity, ease: "linear" }}
                />
                <div className="absolute inset-0 flex items-center justify-center">
                  <motion.div 
                    className="text-white font-serif text-sm font-medium"
                    animate={{ opacity: [0.5, 1, 0.5] }}
                    transition={{ duration: 1.5, repeat: Infinity }}
                  >
                    AI
                  </motion.div>
                </div>
              </div>
              <div className="space-y-2">
                <h2 className="serif text-3xl font-medium">Analyzing your features...</h2>
                <p className="text-white/70 italic">
                  GlowGuide is curating your personalized beauty experience...
                </p>
              </div>
            </motion.div>
          )}

          {state === 'results' && result && (
            <motion.div
              key="results"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="max-w-6xl w-full grid grid-cols-1 lg:grid-cols-12 gap-12"
            >
              {/* Left Column: Image and Profile */}
              <div className="lg:col-span-4 space-y-8">
                <div className="aspect-[3/4] rounded-[40px] overflow-hidden shadow-2xl border-8 border-white">
                  <img src={image!} alt="Your Profile" className="w-full h-full object-cover" />
                </div>
                
                <div className="bg-[#ffffff05] backdrop-blur-md rounded-[32px] p-8 shadow-2xl border border-white/10 space-y-6">
                  <h3 className="serif text-2xl font-medium text-white border-b border-white/10 pb-4">Your Profile</h3>
                  <div className="space-y-4">
                    <ProfileItem label="Skin Tone" value={result.skinTone} />
                    <ProfileItem label="Undertone" value={result.undertone} />
                    <ProfileItem label="Face Shape" value={result.faceShape} />
                    <ProfileItem label="Skin Type" value={result.skinType} />
                  </div>
                </div>

                <div className="flex flex-col gap-4">
                  <button
                    onClick={downloadGuide}
                    className="w-full py-4 rounded-full bg-gradient-to-r from-[#d4587e] to-[#e8a0c0] shadow-[0_0_20px_rgba(232,160,192,0.3)] hover:shadow-[0_0_30px_rgba(232,160,192,0.5)] text-white hover:scale-[1.02] transition-all font-medium flex items-center justify-center gap-2"
                  >
                    <Download size={20} />
                    Download Guide
                  </button>
                  
                  <button
                    onClick={reset}
                    className="w-full py-4 rounded-full border border-white/20 hover:border-white/40 hover:bg-white/5 text-white backdrop-blur-sm transition-all font-medium flex items-center justify-center gap-2"
                  >
                    <RefreshCw size={20} />
                    New Analysis
                  </button>
                </div>
              </div>

              {/* Right Column: Recommendations */}
              <div className="lg:col-span-8 space-y-8">
                <div className="space-y-2">
                  <span className="text-xs uppercase tracking-widest font-bold text-[#f5a8c8]">Personalized Guide</span>
                  <h2 className="serif text-5xl md:text-6xl font-light text-white">Recommended for you</h2>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <RecCard 
                    title="Foundation & Base" 
                    content={result.recommendations.foundation} 
                    icon={<User size={20} />} 
                  />
                  <RecCard 
                    title="Lip Color" 
                    content={result.recommendations.lipstick} 
                    icon={<Heart size={20} />} 
                    swatch={result.recommendations.lipstickHex}
                  />
                  <RecCard 
                    title="Eyeshadow Palette" 
                    content={result.recommendations.eyeshadow} 
                    icon={<Palette size={20} />} 
                    swatch={result.recommendations.eyeshadowHex}
                  />
                  <RecCard 
                    title="Blush & Glow" 
                    content={result.recommendations.blush} 
                    icon={<Sparkles size={20} />} 
                    swatch={result.recommendations.blushHex}
                  />
                </div>

                <div className="bg-[#ffffff05] border border-white/10 backdrop-blur-md text-white rounded-[40px] p-10 shadow-2xl space-y-6">
                  <div className="flex items-center gap-3 text-[#f5a8c8]">
                    <Info size={24} />
                    <h3 className="serif text-3xl italic text-white">Style: {result.recommendations.overallStyle}</h3>
                  </div>
                  <div className="prose-custom max-w-none opacity-90 leading-relaxed font-light text-white/80">
                    <Markdown>{result.explanation}</Markdown>
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      {/* Footer */}
      <footer className="p-12 border-t border-white/10 text-white text-center space-y-4">
        <p className="serif text-xl italic opacity-60">"Beauty begins the moment you decide to be yourself."</p>
        <p className="text-xs uppercase tracking-[0.2em] opacity-40 font-bold">© 2026 GlowGuide AI</p>
      </footer>
    </div>
  );
}

function ProfileItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between items-center py-2 border-b border-white/10 last:border-0">
      <span className="text-sm font-semibold uppercase tracking-wider opacity-60 text-white">{label}</span>
      <span className="font-medium text-white/90">{value}</span>
    </div>
  );
}

function RecCard({ title, content, icon, swatch }: { title: string; content: string; icon: React.ReactNode; swatch?: string }) {
  const searchUrl = `https://www.google.com/search?q=${encodeURIComponent(content + ' makeup')}`;
  
  return (
    <div className="bg-[#ffffff05] backdrop-blur-md p-8 rounded-[32px] shadow-2xl border border-white/10 space-y-4 hover:bg-[#ffffff08] transition-all group">
      <div className="flex justify-between items-start">
        <div className="flex items-center gap-3 text-[#f5a8c8]">
          <div className="p-2 rounded-xl bg-white/5">{icon}</div>
          <h4 className="font-bold uppercase tracking-widest text-xs">{title}</h4>
        </div>
        {swatch && (
          <div className="relative group/swatch">
            <div 
              className="w-10 h-10 rounded-full border-2 border-white focus:outline-none shadow-lg transition-transform hover:scale-110 cursor-help" 
              style={{ backgroundColor: swatch }}
            />
            <div className="absolute top-full right-0 mt-2 p-2 bg-[#110714] text-white border border-white/10 text-xs rounded-lg opacity-0 group-hover/swatch:opacity-100 transition-opacity whitespace-nowrap pointer-events-none z-10 shadow-xl">
              {swatch}
            </div>
          </div>
        )}
      </div>
      <p className="text-lg leading-relaxed text-white/80 font-light">{content}</p>
      <a 
        href={searchUrl} 
        target="_blank" 
        rel="noopener noreferrer"
        className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#f5a8c8] opacity-0 group-hover:opacity-100 transition-opacity"
      >
        <Search size={14} />
        Find Products
      </a>
    </div>
  );
}

function RefreshCw({ size }: { size: number }) {
  return (
    <svg 
      width={size} 
      height={size} 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth="2" 
      strokeLinecap="round" 
      strokeLinejoin="round"
    >
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M3 21v-5h5" />
    </svg>
  );
}

function Modal({ type, onClose }: { type: ModalType; onClose: () => void }) {
  const content = {
    'how-it-works': {
      title: 'How GlowGuide Works',
      body: `
### 1. Advanced Vision Analysis
When you take a selfie, our AI uses advanced computer vision to map your facial structure and identify key features.

### 2. Color Theory Integration
We analyze your skin's undertones (Cool, Warm, or Neutral) and overall tone to find colors that naturally complement your complexion.

### 3. Personalized Curation
Gemini Pro processes this data to curate a specific makeup palette, from foundation shades to lipstick colors, tailored specifically for you.
      `
    },
    'privacy': {
      title: 'Your Privacy Matters',
      body: `
### Real-time Processing
Your images are processed in real-time to generate recommendations. We do not store your photos on our servers permanently.

### Secure Analysis
All analysis is performed using secure API connections. Your personal data is used solely for providing beauty recommendations during your session.

### Control
You have full control over your camera and data. No information is shared with third parties without your explicit consent.
      `
    },
    'about': {
      title: 'About GlowGuide AI',
      body: `
### Beauty Reimagined
GlowGuide AI was born from the idea that beauty should be accessible and personalized. We leverage the latest in Artificial Intelligence to help you discover your best self.

### Our Mission
To empower individuals with professional-grade beauty advice through the power of technology. We believe everyone deserves to feel confident in their own skin.
      `
    }
  }[type as Exclude<ModalType, 'none'>];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-brand-ink/40 backdrop-blur-md"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0, y: 20 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.9, opacity: 0, y: 20 }}
        className="bg-brand-cream w-full max-w-2xl rounded-[40px] shadow-2xl overflow-hidden relative"
        onClick={(e) => e.stopPropagation()}
      >
        <button 
          onClick={onClose}
          className="absolute top-8 right-8 p-2 rounded-full hover:bg-brand-rose transition-colors text-brand-ink/40 hover:text-brand-ink"
        >
          <X size={24} />
        </button>
        
        <div className="p-12 space-y-8 text-center">
          <div className="space-y-2">
            <span className="text-xs uppercase tracking-widest font-bold text-brand-ink">Information</span>
            <h2 className="serif text-4xl font-medium">{content.title}</h2>
          </div>
          
          <div className="prose-custom max-w-none text-brand-ink/80 leading-relaxed mx-auto">
            <Markdown>{content.body}</Markdown>
          </div>

          <button
            onClick={onClose}
            className="w-full py-4 bg-brand-ink text-brand-cream rounded-full font-medium hover:scale-[1.02] transition-transform shadow-lg"
          >
            Got it
          </button>
        </div>
      </motion.div>
    </motion.div>
  );
}
